apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: stihk-letsencrypt@oisann.net
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}